name: Build Flutter App

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3️⃣ Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release

      # 5️⃣ Upload hasil build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

    